---
title: The æternity crypto foundation
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
permalink: pretty
theme:
  name: 'material'
  palette:
    primary: 'pink'
    accent: 'white'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
